# Generated by Django 2.2.7 on 2019-11-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keta', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
